spring:
  datasource:
    host: localhost
    port: 27017
    database: boldb
    authentication-database: admin
    username: root
    password: root
  jpa:
    show-sql: true

#spring:
#  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/boldb}
#    username: postgres
#    password: admin
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: validate
#    open-in-view: false
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
